version: '3.8'

services:
  app:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    container_name: lara_sham
    ports:
      - "8099:80"
    volumes:
      - ../codes:/var/www
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./supervisor/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
